GET http://localhost:5066/meetings

###
POST http://localhost:5066/meetings
Content-Type: application/json

{
    "Title": "a",
    "Summary": "b",
    "ScheduledDate": "2018-06-12T19:30",
    "Place": "c"
}

###
POST http://localhost:5066/meetings/1/agendapoints
Content-Type: application/json

{
    "Description": "a",
    "HasLegalEffect": true
}

###
DELETE http://localhost:5066/users/2

###
POST http://localhost:5066/login
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin"
}

###
GET http://localhost:5066/users
Authorization: Bearer 