GET http://localhost:5066/meetings

###
DELETE http://localhost:5066/users/2

###
POST http://localhost:5066/login
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin"
}

###
GET http://localhost:5066/users
Authorization: Bearer 